### ISSUE TITLE
Visual Studio 2017?

### ISSUE THREAD

**Issue by ehalsey** [IntuitDeveloper/Oauth2-MVC5-DotnetSampleApp#1]
Has anyone been successful running the sample in VS2017?  I'm getting a bunch of assembly reference errors.  I'm targeting .NET Framework 4.6.1 and have run Update-Package to update all of the NuGet packages.  Looks like it might be the same as https://github.com/IntuitDeveloper/OAuth2-Dotnet_UsingSDK/issues/2. I will try following those recommendations and report back.

**Comment by ehalsey** [comment]
I manually added the missing assembly references from the packages folder and I was able to get it to run and it appears to be working.

**Comment by nimisha84** [comment]
Did the restore Nuget packages option not work for you?

**Comment by nimisha84** [comment]
I made changes to the checkin this time.See if you still face issues.

**Comment by ehalsey** [comment]
Seems to have fixed it
